### ISSUE TITLE
GitHub Sponsors?

### ISSUE THREAD

**Issue by kiwicopple** [lquixada/cross-fetch#119]
Hey @lquixada, yours is the only package we use inside the JS libs at Supabase.

Would you consider setting up GitHub sponsors so that we can sponsor you? Alternatively if you create an account on Open Collective we can pay you through that. 

Feel free to close this once you've read it - you can reach out to me on twitter (@kiwicopple) or email (copple at supabase dot io)

**Comment by lquixada** [comment]
@kiwicopple Thanks for this lovely suggestion. Really appreciate it! Sorry for the late reply. I've never considered being sponsored but I'll keep that in mind for the future. In the meantime, I'll closing this. Thanks a lot!
