### ISSUE TITLE
No `Response.body` ReadableStream?

### ISSUE THREAD

**Issue by Cobertos** [lquixada/cross-fetch#121]
I'm getting undefined on the `Response.body` parameter when it seems like it should be a `ReadableStream`? at least according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/body) and [WhatWG](https://fetch.spec.whatwg.org/#ref-for-dom-body-body%E2%91%A0)

`fetch` is browser default fetch, `_fetch` is `cross-fetch`

![image](https://user-images.githubusercontent.com/6759176/147436989-517a9553-231e-423c-8ae0-5f4fbe22e794.png)

Is this expected?

**Comment by lquixada** [comment]
hey @Cobertos, thanks for reporting this issue. `cross-fetch` is just a proxy for `node-fetch` and `whatwg-fetch`, it doesn't implement any spec. Since this is happening in the browser, please refer to the [whatwg-fetch repo](https://github.com/github/fetch/) and let them know about it!

**Comment by Cobertos** [comment]
Ah I see, looks like it's been an ask for [7-ish years](https://github.com/github/fetch/issues/198) and won't be added.

Thanks!
