### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [lquixada/cross-fetch#122]
Hey there!

I belong to an open source security research community, and a member (@ranjit-git) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by lquixada** [comment]
@JamieSlome thanks for taking the time to open this issue! A [SECURITY.md](https://github.com/lquixada/cross-fetch/blob/main/SECURITY.md) file has been created.

**Comment by JamieSlome** [comment]
@lquixada - thanks for creating the `SECURITY.md` 👍 

We will get further details sent over to the elected e-mail address shortly. In the meantime, the report can be accessed directly here:
https://huntr.dev/bounties/ab55dfdd-2a60-437a-a832-e3efe3d264ac

It is private and only accessible to you @lquixada 👍

**Comment by lquixada** [comment]
thanks @JamieSlome ! will take a look!

**Comment by JamieSlome** [comment]
@lquixada - great, on call if you need me for any support, plus @ranjit-git for any questions regarding the report 😃
