### ISSUE TITLE
Tag 3.1.5 wasn't successfully published to the npm registry

### ISSUE THREAD

**Issue by sergio-domingues** [lquixada/cross-fetch#128]
The `npm publish` [step](https://github.com/lquixada/cross-fetch/runs/4889554870?check_suite_focus=true) for `v3.1.5` failed.

It's an important version tag since it fixes -> https://github.com/lquixada/cross-fetch/pull/124#issue-1107437836

**Comment by sergio-domingues** [comment]
@lquixada any info on this?

**Comment by lquixada** [comment]
the step failed because the `3.1.5` was published from my machine before the CI job. The version is already available on npm: https://www.npmjs.com/package/cross-fetch
