### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [lquixada/cross-fetch#134]
A potential security vulnerability has been disclosed for this repo https://huntr.dev/bounties/ab55dfdd-2a60-437a-a832-e3efe3d264ac/  3 months ago .
But i see it still not addressed .
Kindly validate the bug

**Comment by janaagaard75** [comment]
Do you have another link to the report, where it’s publicly available, @ranjit-git?

**Comment by lquixada** [comment]
Issue is unclear. This PR will be closed until more info is provided.

**Comment by ranjit-git** [comment]
@lquixada 
Plz provide a security email here https://github.com/lquixada/cross-fetch/issues/122
So that team can send vulnerability details

**Comment by lquixada** [comment]
@ranjit-git a [SECURITY.md](https://github.com/lquixada/cross-fetch/blob/main/SECURITY.md) has been created! Thanks!
