### ISSUE TITLE
Cross fetch throw an error  [ReferenceError: XMLHttpRequest is not defined]

### ISSUE THREAD

**Issue by yasirrafiq33** [lquixada/cross-fetch#142]
This is specific case with nextJs middleware. The package is working fine everywhere but when we try to use it in NEXTJS middleware its throw error. 
The middleware is using **edge runtime**. 
https://nextjs.org/docs/api-reference/edge-runtime

**Comment by bebejane** [comment]
I'm seeing the same error with Vercel edge api functions
https://nextjs.org/docs/api-routes/edge-api-routes

**Comment by perry-mitchell** [comment]
Seeing the same issue with background (service worker) scripts in Chrome extensions running on the new manifest V3. Why am I seeing XMLHttpRequest in `cross-fetch`?

**Comment by Tomas2D** [comment]
Does anyone resolves it?

**Comment by perry-mitchell** [comment]
Gave up waiting, released [my own](https://github.com/buttercup/fetch).

**Comment by Tomas2D** [comment]
@perry-mitchell , I solve it this way

https://github.com/Tomas2D/pagerduty-calculator/blob/main/src/polyfill.ts
https://github.com/Tomas2D/pagerduty-calculator/blob/main/vite.config.ts

**Comment by perry-mitchell** [comment]
> @perry-mitchell , I solved it this way
> 
> 
> 
> https://github.com/Tomas2D/pagerduty-calculator/blob/main/src/polyfill.ts
> 
> https://github.com/Tomas2D/pagerduty-calculator/blob/main/vite.config.ts

But then you're not really using fetch 😅. I needed it in my case as I need to support service workers, which don't provide a working XHR.

**Comment by Tomas2D** [comment]
You are right, mine is just for NodeJS / Browser environment, not workers. I will use your solution, once I will need to make it work in service workers 👍🏻

**Comment by perry-mitchell** [comment]
Your solution is completely valid of course if the interface of fetch is all that matters. Cheers 👍

**Comment by nwarpy** [comment]
I've created a way to disable cross-fetch if you don't need it.

https://github.com/nwarpy/disable-cross-fetch

**Comment by mellunar** [comment]
This issue also affects Cloudflare Wrangler

**Comment by Mnigos** [comment]
I also have this issue

**Comment by lquixada** [comment]
I've been working on version 4 of `cross-fetch` to fix this issue. If anyone's interested, please run `npm install cross-fetch@latest-v4.x` in your project and give it a try. Let me know if any issues come up.

**Comment by lquixada** [comment]
Version 4 has been officially released with the fix. Please check it out: `npm install cross-fetch`.
