### ISSUE TITLE
TypeError: data.getReader is not a function

### ISSUE THREAD

**Issue by louis030195** [lquixada/cross-fetch#165]
Hi, your lib is very helpful, thanks a lot 🙏

I'm facing some issue with the exact code that was working fine using browser fetch when trying to use `cross-fetch`, this is a snippet of what I'm trying to run:

```ts
const response = await fetch(url, {
    method: 'POST',
    headers: headers,
    body: body,
  })

  if (!response.ok) {
    // assuming the error is a JSON object
    const message = await response.json()
    throw new Error(message)
  }

  // This data is a ReadableStream
  const data = response.body
  if (!data) {
    return
  }

  const reader = data.getReader()
```

Where my API is returning a `Response` which is a stream

I get a `TypeError: data.getReader is not a function`

The error disappear when I comment `import fetch from "cross-fetch"`

Any idea? Should I use a different API with `cross-fetch`? Any help would be highly appreciated 🔥

**Comment by louis030195** [comment]
used https lib intead

**Comment by samheutmaker** [comment]
@louis030195  what is https lib? Can you provide a link?

**Comment by louis030195** [comment]
@samheutmaker sorry this is my workaround now https://github.com/different-ai/embedbase/blob/2973555c3fa3d5aab2dc8e7278fe4b9e0a1e597d/sdk/embedbase-js/src/utils.ts#L135
