### ISSUE TITLE
Can't upload file using cross-fetch

### ISSUE THREAD

**Issue by himanshugpt** [lquixada/cross-fetch#2]
I am trying to upload a csv file using cross fetch with react-redux and I am getting Uncaught (in promise) Error: unsupported BodyInit type error. Full Error Trace:
```javascript
Uncaught (in promise) Error: unsupported BodyInit type
at Request.Body._initBody (browser.js:227)
at new Request (browser.js:340)
at browser.js:422
at new Promise (<anonymous>)
at self.fetch (browser.js:421)
at Dropzone.RenderDropZoneInput._this.onDrop (RenderDropZoneInput.js:17)
at Dropzone.onDrop (index.js:229)
at Object.executeOnChange (LinkedValueUtils.js:132)
at ReactDOMComponent._handleChange (ReactDOMInput.js:241)
at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
at executeDispatch (EventPluginUtils.js:85)
at Object.executeDispatchesInOrder (EventPluginUtils.js:108)
at executeDispatchesAndRelease (EventPluginHub.js:43)
at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:54)
at Array.forEach (<anonymous>)
at forEachAccumulated (forEachAccumulated.js:24)
at Object.processEventQueue (EventPluginHub.js:254)
at runEventQueueInBatch (ReactEventEmitterMixin.js:17)
at Object.handleTopLevel [as _handleTopLevel] (ReactEventEmitterMixin.js:27)
at handleTopLevelImpl (ReactEventListener.js:72)
at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:143)
at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
at Object.batchedUpdates (ReactUpdates.js:97)
at dispatchEvent (ReactEventListener.js:147)

```
Source Code:
```javascript
class RenderDropZoneInput extends Component {
    onDrop = (acceptedFiles, rejectedFiles) => {
    const { onChange } = this.props.input
    const files = this.props.input.value || Immutable.List()
    const newFiles = Immutable.List(acceptedFiles)
    const allFiles = files.concat(newFiles)
    onChange(allFiles)
    console.log(acceptedFiles);
     let uri = "http://localhost:8080/api/uplaod"
     fetch(uri, {
      method: 'POST',
      mode: 'cors',
      headers: { 'Content-Type': 'application/octet-stream' },
      body: acceptedFiles[0]
    })

  }

  render() {
    const files = this.props.input.value
    return (
      <div>
        <CustomDropzone onDrop={this.onDrop} multiple={true}>
          {files.size ?
            files.map((file) => <img key={file.name} src={file.preview} style={{ width: '200px', maxWidth: '400px', flexGrow: 1, opacity: 0.5 }} alt='' />)
            : <div><p>Click on me!</p></div>}
        </CustomDropzone>
      </div>
    )
  }
}

export default RenderDropZoneInput
```

You can reproduce or access full project here: https://codesandbox.io/s/z39y9mlwq4

Steps to reproduce: Try uploading a file, the error will be displayed.

I have also tried using FormData
```javascript
let form = new FormData()
form.append('file', acceptedFiles[0]);
return fetch(uri, {
  method: 'POST',
  mode: 'cors',
  headers: { 'Content-Type': 'application/octet-stream' },
  body: form//acceptedFiles[0]
})
```

**Comment by lquixada** [comment]
hi @himanshugpt! thanks for the report! however, cross-fetch is just a proxy to other third-party libraries. Since you're running this code in a browser environment, I suggest to open this issue on [github/fetch](https://github.com/github/fetch) which is the library cross-fetch proxies to.

**Comment by himanshugpt** [comment]
Closing this one. Moved to fetch: https://github.com/github/fetch/issues/601

**Comment by davidrossjones** [comment]
Having the same issue trying to upload a file with fetch. Using FormData and not setting a Content-Type as below:

~~~
const form = new FormData();
    form.append('data', file);

    fetch('http://localhost:4000/upload', {
      method: 'POST', body: form
    })
      .then(res => res.json())
      .then(json => console.log(json))
      .catch(err => console.error(err));
~~~

See the SO question (https://stackoverflow.com/questions/48876058/using-fetch-api-with-cross-fetch-polyfill-to-upload-file-on-file-input-change) and answer:

~~~
Turns out your import fetch from "cross-fetch" is shimming fetch incorrectly, by breaking the parsing of blobs and FormData. Just remove the import and see that everything works.
~~~

Removing `import fetch from "cross-fetch"` and swapping out for `import fetch from "node-fetch"` causes the fetch request to work as expected for me on Node 8.5.

**Comment by himanshugpt** [comment]
This is moved to fetch: github/fetch#601 as its more aligned to fetch api failure.

**Comment by kueda** [comment]
@himanshugpt, did you ever get your example working given the feedback in https://github.com/github/fetch/issues/601?

@lquixada, is there a reason `cross-fetch` doesn't use the React Native version of fetch in React Native? Seems like that would address this issue regardless of what's going on in the github fetch package.

**Comment by himanshugpt** [comment]
@kueda I had to use `isomorphic-fetch` to make it work. As you must have noticed that real issue is https://stackoverflow.com/questions/48876058/using-fetch-api-with-cross-fetch-polyfill-to-upload-file-on-file-input-change and not about how is your form data structured.

**Comment by lquixada** [comment]
@kueda actually if a native fetch is present on the environment, cross-fetch uses it. That includes React Native.

@himanshugpt recently we fixed an issue regarding FormData on cross-fetch. Do you mind testing it again?

**Comment by tiagoalves** [comment]
I just came across this issue with cross-fetch v1.1.1 in React Native and after the upgrade to the latest version (v2.1.0) I can confirm that uploads with FormData are working. Thanks!

**Comment by lquixada** [comment]
@tiagoalves that's great! thanks!

**Comment by Mikhail-MM** [comment]
@lquixada I was receiving an invalid BodyInit error when using `cross-fetch` with a FormData upload - this error was not present when using native implementation and removing the cross-fetch import. However, after updating to (v2.1.0) the error is fixed and it fetch is working as expected with the FormData body.

**Comment by tiagoalves** [comment]
As mentioned, I was able to successfully use FormData in the latest version of cross-fetch. However, that was only while in debug mode of a **React Native** application where the JS code is interpreted by Chrome.

I'm not being able to use FormData while running in release mode where the JS code is interpreted by Android's JS engine. I haven't tested it with iOS in release mode yet.

The exception I get is the same `unsupported BodyInit type`.

Can we reopen this issue?
