### ISSUE TITLE
Update whatwg-fetch to v3.0.0

### ISSUE THREAD

**Issue by teppeis** [lquixada/cross-fetch#25]
Released: https://github.com/github/fetch/releases/tag/v3.0.0

**Comment by yordis** [comment]
@lquixada hey mate, could you upgrade the packages to the latest version?

**Comment by lquixada** [comment]
Yes but currently I'm busy moving to New York. This leaves me little time to do it. There's also an upgrade on the node-fetch package that is not trivial.

**Comment by martinheidegger** [comment]
ping

**Comment by lquixada** [comment]
working on it!

**Comment by lquixada** [comment]
done!
