### ISSUE TITLE
fetch is undefined in React Native

### ISSUE THREAD

**Issue by tgamauf** [lquixada/cross-fetch#26]
I've written an API wrapper that uses cross-fetch to make it compatible with Browsers, Node and React Native. Now, if I test it with Node it works perfectly, but if I use the wrapper in React Native if fails with the following error: `TypeError: undefined is not a function (evaluating 'cross_fetch_1.default(url, init)')`. If I print the type of `cross_fetch_1` I get:
```
{ [Function]
   polyfill: true,
  Response: { [Function: Response] error: [Function], redirect: [Function] },
  Request: [Function: Request],
  Headers: [Function: Headers] }
```
and "undefined" for either `cross_fetch_1.default` or `cross_fetch_1.fetch`.

The library was developed in Typescript, so the cross_fetch_1 variable is created by the TS compiler. You can find the Typescript code here https://github.com/tgamauf/onetimesecret-api/blob/1b8edff66bde11807c8ff7d29030b4d3e6661277/lib/request.ts#L150 and the compiled JS here https://github.com/tgamauf/onetimesecret-api/blob/1b8edff66bde11807c8ff7d29030b4d3e6661277/lib/request.js#L179.

As far as I can tell I am using the module as it is supposed to be used. What could cause this?

**Comment by mattmccutchen** [comment]
Also reported [here](https://stackoverflow.com/questions/52917733).  `cross-fetch` should probably add a default export to `browser-ponyfill.js`, just as `node-ponyfill.js` has.

**Comment by tgamauf** [comment]
As Matt noted in the Stackoverflow question, activating `esModuleInterop` in the Typescript compiler is a workaround. I agree, this should be fixed as it isn't really expected behavior.

**Comment by sondremare** [comment]
@lquixada Do you have an estimate of when this will be released?

**Comment by lquixada** [comment]
@sondremare hopefully this weekend.
