### ISSUE TITLE
Types error in index.d.ts for nodejs

### ISSUE THREAD

**Issue by KyloJorgensen** [lquixada/cross-fetch#35]
![image](https://user-images.githubusercontent.com/18789138/50727193-cd00be80-10d4-11e9-9f0a-61cf580db0a4.png)

usesing vscode to write nodejs server code

**Comment by lquixada** [comment]
Closing this since there was no answer.

**Comment by esetnik** [comment]
@lquixada please reopen. I have the same error as @KyloJorgensen. I don't think those are global types. I don't see them defined in the node type definitions at least.

```
/builds/x/api/node_modules/cross-fetch/index.d.ts (1,27): Cannot find name 'fetch'.
/builds/x/api/node_modules/cross-fetch/index.d.ts (2,27): Cannot find name 'Request'.
/builds/x/api/node_modules/cross-fetch/index.d.ts (3,27): Cannot find name 'Response'.
/builds/x/api/node_modules/cross-fetch/index.d.ts (4,31): Cannot find name 'Headers'. Did you mean 'headers'?
```

**Comment by lquixada** [comment]
hey @esetnik, can you try going to your tsconfig.json > compilerOptions > libs and add "dom" to the list?

**Comment by will-wow** [comment]
I was seeing the same issue - `import fetch from "cross-fetch";` wasn't picking up any types for `fetch`, and the `index.d.ts` file showed `Cannot find name 'fetch'.` 

Adding `dom` to `libs` fixed the issue for me. Thanks @lquixada!

**Comment by esetnik** [comment]
I don't think `dom` should be added to `libs` for node environments. This adds a lot of types that are only available in the browser.

**Comment by lquixada** [comment]
@esetnik you're right! however, if you follow the the fetch, Request, Response and Header declaration inside the [lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts), you'll realize that those are very deeply nested declarations. Unfortunately, there's no easy way to extract and maintain them. It would be needed a lot of copy and paste and it would be hard to keep track of any update.

In my opinion, having a single source of truth (the lib.dom.d.ts in this case) is more valuable than saving a few kilobytes that users would not have to download anyway.
