### ISSUE TITLE
Replace node-fetch with slim-fetch?

### ISSUE THREAD

**Issue by cktang88** [lquixada/cross-fetch#36]
https://www.npmjs.com/package/slim-fetch is a new library that has basically identical code to node-fetch, but stripped away unnecessary parts of the distribution (eg. node-fetch actually has three copies of the same code for backwards compatibility purposes).

**Comment by lquixada** [comment]
this project is still in its infancy and lacks a lot of node-fetch features: tests, coverage, builds, community and so on. Closing this issue for now.
