### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by roccomuso** [lquixada/cross-fetch#47]
Are errors handled the same way between `node-fetch` and `whatwg-fetch`?
Do this lib ensure this?

**Comment by lquixada** [comment]
No, this lib is only a proxy. The errors should be handled the same way since both `node-fetch` and `whatwg-fetch` implements a common subset of the standard [Fetch specification](https://fetch.spec.whatwg.org/).

**Comment by roccomuso** [comment]
ok thanks
