### ISSUE TITLE
Version 3.0.3 buffer issue

### ISSUE THREAD

**Issue by ethan-pearce** [lquixada/cross-fetch#50]
In the latest version of the package (3.0.3) instead of a JSON response you get a buffer 

`{"data": [123, 34, 116, 111, 107, 101, 110, 34, 58, 34, 54, 102, 54, 56, 51, 50, 51, 49, 45, 48, 98, 48, 52, 45, 52, 102, 48, 55, 45, 97, 51, 51, 55], "type": "Buffer"}
`

**Comment by VilmaRamos** [comment]
This is related with the upgrade to node-fetch latest version. Since version node-fetch@2.4.0, if body is a string it will be buffered.  See this [PR](https://github.com/bitinn/node-fetch/commit/7d3293200a91ad52b5ca7962f9d6fd1c04983edb#diff-f0c01727e5628483090afb5bc8c36be6L37)

**Comment by ethan-pearce** [comment]
This probably should have been marked as a breaking change !

**Comment by lquixada** [comment]
Hi @ethan-pearce! Thanks for reporting the issue. Can you provide a snippet of your code that broke because of this change?

**Comment by lquixada** [comment]
Closing this issue since there was no response.
