### ISSUE TITLE
Don't bundle whatwg-fetch in browser entry

### ISSUE THREAD

**Issue by jacobrask** [lquixada/cross-fetch#51]
Instead of bundling the entire whatwg-fetch, could it be a `require()` call, like in `isomorphic-fetch` and `isomorphic-unfetch`?

The `browser` field is the default entry point for all Webpack builds, which means that anyone using Webpack and accidentally including some other package that also pulls in `whatwg-fetch` will get duplicate copies.

**Comment by lquixada** [comment]
You're right! the issue with importing/requiring `whatwg-fetch` is that it's going to polyfill your environment. It's not going to be an option anymore, it will be mandatory. Although there will be duplicate code in node_modules, it's going to be a very small one. So it's a cheap price to pay to have a clean ponyfill.

**Comment by jacobrask** [comment]
Ok, I see the reason then, but whatwg-fetch is [almost 8kB](https://bundlephobia.com/result?p=whatwg-fetch@3.0.0), I wouldn't consider that negligible, it all adds up in a large project.

**Comment by lquixada** [comment]
Unfortunately I don't see any alternative to that. Closing the issue.
