### ISSUE TITLE
Integrated tests in Suacelabs Failing for some Safari, Firefox versions

### ISSUE THREAD

**Issue by ananyasen** [lquixada/cross-fetch#55]
Hi there, I am trying to use cross-fetch to replace isomorohic-fetch. 
We need to support all browsers  and IOS/Android through React Native.

Just noticed this. Could you please help.

https://www.npmjs.com/package/cross-fetch#supported-environments
<img width="572" alt="Screen Shot 2019-07-22 at 8 19 24 PM" src="https://user-images.githubusercontent.com/1248490/61680344-08a05600-acbe-11e9-8d19-3eb2a446aa33.png">

**Comment by lquixada** [comment]
hey @ananyasen, unfortunately the cross-browser service has not been much reliable lately. Sometimes the tests gets stuck in these browsers and saucelabs can't report the results. That's intermittent.

As an alternative, you can run the specs manually. Please open the above failing browsers on the url: https://lquixada.github.io/cross-fetch/test/browser/saucelabs/. You'll see every test passing.

**Comment by ananyasen** [comment]
Awesome thanks!
https://lquixada.github.io/cross-fetch/test/browser/saucelabs/ works.
