### ISSUE TITLE
Not working on chrome

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [lquixada/cross-fetch#57]
It is working on desktop and latest android phone. But when i test on followings, it is not working

Chrome 78.0.3904.108
Android 4.4.2 H60-L04 Build/HDH60-L04

Agent:Mozilla/5.0 (Linux; Android 4.4.2; H60-L04 Build/HDH60-L04) Apple WebKit/537.36 (KHTML, like Gecko) version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

**Comment by beenotung** [comment]
What do you mean by not working?
Any error messages?

**Comment by lquixada** [comment]
Closing this issue since no further info was provided.
