### ISSUE TITLE
Is user-agent supported?

### ISSUE THREAD

**Issue by dandv** [lquixada/cross-fetch#65]
There's a long discussion at https://github.com/whatwg/fetch/issues/37 about user-agent, which apparently is [no longer forbidden](https://github.com/whatwg/fetch/issues/37#issuecomment-645666012).

Is that header [still ignored](https://github.com/lquixada/cross-fetch/issues/42#issuecomment-495927153) by `cross-fetch`? The following sent a user agent of `node-fetch/1.0 (+https://github.com/bitinn/node-fetch) `.

```js
fetch(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36',  // Chrome Android, to maybe get a slimmer page version
    },
  })
```

**Comment by lquixada** [comment]
thanks for the issue report! `cross-fetch` is just a proxy for [whatwg-fetch](https://github.com/github/fetch/) in a browser and [node-fetch](https://github.com/bitinn/node-fetch/) in Node. So it will honor whatever those libs allow. If you've got the `node-fetch/1.0` user agent, `node-fetch` is being used, not `whatwg-fetch`.

**Comment by dandv** [comment]
Right! Thanks for the clarification :)
