### ISSUE TITLE
Update to node-fetch v3?

### ISSUE THREAD

**Issue by dandv** [lquixada/cross-fetch#66]
[Looks like](https://github.com/lquixada/cross-fetch/issues/65) node-fetch renamed its UA along with its repo from `node-fetch/1.0 (+https://github.com/bitinn/node-fetch` to something without `bitinn` at some point, because I [can't find "bitinn"]( https://github.com/node-fetch/node-fetch/search?q=bitinn&type=Code) in its code.

**Comment by lquixada** [comment]
will update to node-fetch v3 as soon as a stable version is published. Regarding the `user-agent` issue, here's what you should know: https://github.com/node-fetch/node-fetch/blob/master/docs/v3-UPGRADE-GUIDE.md#changed-default-user-agent
