### ISSUE TITLE
When init.headers are native Headers, they won't get send

### ISSUE THREAD

**Issue by FokkeZB** [lquixada/cross-fetch#79]
When `options.headers` already is a native `Headers` object, this will lead to an empty `this.headers`:

https://github.com/lquixada/cross-fetch/blob/22578271d864d24074c455b8a473b46898542f0f/dist/browser-ponyfill.js#L346-L348

This is because the `instanceof` check here is done against the polyfil:

https://github.com/lquixada/cross-fetch/blob/22578271d864d24074c455b8a473b46898542f0f/dist/browser-ponyfill.js#L93-L96

We should either not override `Headers` if it already exists, or keep a reference to the original and include it in the `instanceof` check as well.

**Comment by lquixada** [comment]
hey @FokkeZB ! Thanks for reporting that. `cross-fetch` is just a proxy for `node-fetch` on node environment and `whatwg-fetch` on browsers. The issue you're referring to is on the `whatwg-fetch` side. Please double check if this also happens on https://github.com/github/fetch/.

**Comment by FokkeZB** [comment]
Hey @lquixada - this is indeed happening there as well: https://7k3gx.csb.app/

![](https://cdn.zappy.app/5d7fb2447409aea369edb89219f44d57.png)

**Comment by lquixada** [comment]
Hopefully they will handle this issue! Closing this one.

**Comment by FokkeZB** [comment]
Hope so! Reported at https://github.com/github/fetch/issues/860
