### ISSUE TITLE
Error: Cannot find module 'cross-fetch' without any reason

### ISSUE THREAD

**Issue by aeroideaservices** [lquixada/cross-fetch#81]
while running: npm install without lock file

**Comment by bitworking** [comment]
Same problem

**Comment by lquixada** [comment]
@aeroideaservices I couldn't reproduce this error. What are the simplest steps to do it?

**Comment by bitworking** [comment]
@lquixada I think it's not related to this library but some other package(s) that did a minor upgrade with a breaking change and did move cross-fetch to the peer dependencies. I could fix it by using the yarn.lock file in my dockerfile.

**Comment by lquixada** [comment]
got it! thanks @bitworking !
