### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by tigger9flow** [lquixada/cross-fetch#87]
Seems like `cross-fetch` has a memory leak. Tested in the browser (Google Chrome, 88). The issue is reproduced by simple script (ignore CORS error, it behaves the same when request is resolved) which fires requests in interval:
```
setInterval(() => {
  fetch('https://google.com')
    .then(console.log, console.log)
}, 250)
```
After profiling around 1 minute, we can see that event listeners are constantly growing:

![image](https://user-images.githubusercontent.com/18001933/106926817-299e8f80-671a-11eb-9e0d-b53682579b1d.png)

While they are fine with native `fetch`:

![image](https://user-images.githubusercontent.com/18001933/106926837-2e634380-671a-11eb-8324-6471b9b97a38.png)

**Comment by lquixada** [comment]
hey @tigger9flow ! thanks for reporting that. In the browser, `cross-fetch` is just a wrapper around [whatwg-fetch](https://github.com/github/fetch). Can you check if that's also happening there as well?

Here's some code to help:

```html
<script>
  // Delete native fetch api to force the polyfill installation
  delete window.fetch
  delete window.Request
  delete window.Response
  delete window.Headers
</script>
<script src="https://unpkg.com/whatwg-fetch@3.5.0/dist/fetch.umd.js"></script>
```

If it does, please report the issue on https://github.com/github/fetch/issues. Otherwise, please let me know so I can take a look.

**Comment by tigger9flow** [comment]
Hey, @lquixada! You're totally right, it's reproduced in `whatwg-fetch` as well. Sorry for bothering you, I just haven't managed to find the dependency of browser-specific implementation of `fetch`. [Duplicated](https://github.com/github/fetch/issues/901) the issue in `whatwg-fetch` repo. Thank you! :)

**Comment by lquixada** [comment]
no worries @tigger9flow ! happy to help! thanks for reporting the issue on `whatwg-fetch`!
