### ISSUE TITLE
Update browser polyfill to include better error message

### ISSUE THREAD

**Issue by holm** [lquixada/cross-fetch#91]
We are currently seeing some rare instances of the error `Invalid character in header field name` in the wild.

The change in whatwg-fetch at https://github.com/github/fetch/pull/880 will provide us with a better error message, so we can try to understand why this happens. It would be great if the polyfill could be updated and a new version released.

Thanks.

**Comment by lquixada** [comment]
I've been working on version 4 of `cross-fetch` and the `whatwg-fetch` was updated to the latest version (3.6.2). If anyone's interested in checking it out, please run `npm install cross-fetch@latest-v4.x` in your project to give it a try. Let me know if any issues come up.

**Comment by lquixada** [comment]
Version 4 has been officially released with `whatwg-fetch@3.6.2`. Please check it out: `npm install cross-fetch`.
